# Generated by Django 6.0.7 on 2026-08-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_category', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('salary_range', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('key_skills', models.TextField()),
                ('min_qualification', models.CharField(max_length=200)),
                ('experience_years', models.CharField(max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('openings', models.IntegerField()),
                ('benefits', models.TextField(blank=True)),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
