# Generated by Django 6.0.7 on 2026-08-04 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('total_experience', models.CharField(choices=[('0-1 Years', '0-1 Years'), ('1-2 Years', '1-2 Years'), ('2-4 Years', '2-4 Years'), ('4-6 Years', '4-6 Years'), ('6+ Years', '6+ Years')], max_length=20)),
                ('current_role', models.CharField(blank=True, max_length=150)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('notice_period', models.CharField(choices=[('Immediate', 'Immediate'), ('15 Days', '15 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], max_length=20)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Jobportal.job')),
            ],
            options={
                'db_table': 'ApplyForm',
            },
        ),
    ]
