# Generated by Django 6.0.7 on 2026-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0004_applyform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
