# Generated by Django 6.0.7 on 2026-08-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0007_job_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
    ]
