# Generated by Django 6.0.7 on 2026-08-27 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0009_job_posted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('original_name', models.CharField(max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_role', models.CharField(max_length=200)),
                ('resume_data', models.JSONField(default=dict)),
                ('ats_score', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resumes', to=settings.AUTH_USER_MODEL)),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_resumes', to='Jobportal.resume')),
            ],
        ),
    ]
