# Generated by Django 6.0.7 on 2026-09-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0012_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applyform',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
