# Generated by Django 6.0.7 on 2026-09-14 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0016_applyform_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applyform',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job_application'),
        ),
    ]
