# Generated by Django 6.0.7 on 2026-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
